// MIT License
//
// Copyright (c) 2023 Arjen P. van Zanten
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
// associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute,
// sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#ifndef MIDI_CONTROL_H
#define MIDI_CONTROL_H

#include <stdint.h>

typedef enum MIDI_Control {
  MIDI_CTRL_BANK_SELECT = 0,
  MIDI_CTRL_MOD_WHEEL,
  MIDI_CTRL_BREATH_CONTROL,

  MIDI_CTRL_UNDEFINED3,

  MIDI_CTRL_FOOT_PEDAL = 4,
  MIDI_CTRL_PORTAMENTO,
  MIDI_CTRL_DATA_ENTRY,
  MIDI_CTRL_VOLUME,
  MIDI_CTRL_BALANCE,
  MIDI_CTRL_UNDEFINED9,
  MIDI_CTRL_PAN,
  MIDI_CTRL_EXPRESSION,
  MIDI_CTRL_EFFECT1,
  MIDI_CTRL_EFFECT2,

  MIDI_CTRL_UNDEFINED14,
  MIDI_CTRL_UNDEFINED15,

  MIDI_CTRL_GENERAL_A = 16,
  MIDI_CTRL_GENERAL_B,
  MIDI_CTRL_GENERAL_C,
  MIDI_CTRL_GENERAL_D,

  MIDI_CTRL_UNDEFINED20,
  MIDI_CTRL_UNDEFINED21,
  MIDI_CTRL_UNDEFINED22,
  MIDI_CTRL_UNDEFINED23,
  MIDI_CTRL_UNDEFINED24,
  MIDI_CTRL_UNDEFINED25,
  MIDI_CTRL_UNDEFINED26,
  MIDI_CTRL_UNDEFINED27,
  MIDI_CTRL_UNDEFINED28,
  MIDI_CTRL_UNDEFINED29,
  MIDI_CTRL_UNDEFINED30,
  MIDI_CTRL_UNDEFINED31,

  MIDI_CTRL_BANK_SELECT_LSB = 32,
  MIDI_CTRL_MOD_WHEEL_LSB,
  MIDI_CTRL_BREATH_CONTROL_LSB,

  MIDI_CTRL_UNDEFINED35,

  MIDI_CTRL_FOOT_PEDAL_LSB = 36,
  MIDI_CTRL_PORTAMENTO_LSB,
  MIDI_CTRL_DATA_ENTRY_LSB,
  MIDI_CTRL_VOLUME_LSB,
  MIDI_CTRL_BALANCE_LSB,

  MIDI_CTRL_UNDEFINED41, // OFFICIALLY LSB OF UNDEFINED3

  MIDI_CTRL_PAN_LSB = 42,
  MIDI_CTRL_EXPRESSION_LSB,
  MIDI_CTRL_EFFECT1_LSB,
  MIDI_CTRL_EFFECT2_LSB,

  MIDI_CTRL_UNDEFINED46, // OFFICALLY LSB OF UNDEFINED14
  MIDI_CTRL_UNDEFINED47, // OFFICALLY LSB OF UNDEFINED15

  MIDI_CTRL_GENERAL_A_LSB = 48,
  MIDI_CTRL_GENERAL_B_LSB,
  MIDI_CTRL_GENERAL_C_LSB,
  MIDI_CTRL_GENERAL_D_LSB,

  MIDI_CTRL_UNDEFINED52, // OFFICIALLY LSB OF UNDEFINED20.
  MIDI_CTRL_UNDEFINED53, // OFFICIALLY LSB OF UNDEFINED21.
  MIDI_CTRL_UNDEFINED54, // OFFICIALLY LSB OF UNDEFINED22.
  MIDI_CTRL_UNDEFINED55, // OFFICIALLY LSB OF UNDEFINED23.
  MIDI_CTRL_UNDEFINED56, // OFFICIALLY LSB OF UNDEFINED24.
  MIDI_CTRL_UNDEFINED57, // OFFICIALLY LSB OF UNDEFINED25.
  MIDI_CTRL_UNDEFINED58, // OFFICIALLY LSB OF UNDEFINED26.
  MIDI_CTRL_UNDEFINED59, // OFFICIALLY LSB OF UNDEFINED27.
  MIDI_CTRL_UNDEFINED60, // OFFICIALLY LSB OF UNDEFINED28.
  MIDI_CTRL_UNDEFINED61, // OFFICIALLY LSB OF UNDEFINED29.
  MIDI_CTRL_UNDEFINED62, // OFFICIALLY LSB OF UNDEFINED30.
  MIDI_CTRL_UNDEFINED63, // OFFICIALLY LSB OF UNDEFINED31.

  MIDI_CTRL_DAMPER_PEDAL_ON_OFF = 64,
  MIDI_CTRL_PORTAMENTO_ON_OFF,
  MIDI_CTRL_SOSTENUTO_PEDAL_ON_OFF,
  MIDI_CTRL_SOFT_PEDAL_ON_OFF,
  MIDI_CTRL_LEGATO_ON_OFF,
  MIDI_CTRL_HOLD_ON_OFF,

  MIDI_CTRL_SOUND_VARIATION = 70, // AKA SOUND CONTROLLER 1.
  MIDI_CTRL_RESONANCE,            // AKA SOUND CONTROLLER 2.
  MIDI_CTRL_RELEASE_TIME,         // AKA SOUND CONTROLLER 3.
  MIDI_CTRL_ATTACK_TIME,          // AKA SOUND CONTROLLER 4.
  MIDI_CTRL_CUTOFF_FREQUENCY,     // AKA SOUND CONTROLLER 5.
  MIDI_CTRL_SOUND_CONTROLLER6,
  MIDI_CTRL_SOUND_CONTROLLER7,
  MIDI_CTRL_SOUND_CONTROLLER8,
  MIDI_CTRL_SOUND_CONTROLLER9,
  MIDI_CTRL_SOUND_CONTROLLER10,

  MIDI_CTRL_GENERAL_E = 80,
  MIDI_CTRL_GENERAL_F,
  MIDI_CTRL_GENERAL_G,
  MIDI_CTRL_GENERAL_H,
  MIDI_CTRL_PORTAMENTO_ALT,

  MIDI_CTRL_UNDEFINED85,
  MIDI_CTRL_UNDEFINED86,
  MIDI_CTRL_UNDEFINED87,

  MIDI_CTRL_VELOCITY_PREFIX = 88,

  MIDI_CTRL_UNDEFINED89,
  MIDI_CTRL_UNDEFINED90,

  MIDI_CTRL_EFFECT3 = 91, // AKA EFFECT DEPTH 1
  MIDI_CTRL_EFFECT4,      // AKA EFFECT DEPTH 2
  MIDI_CTRL_EFFECT5,      // AKA EFFECT DEPTH 3
  MIDI_CTRL_EFFECT6,      // AKA EFFECT DEPTH 4
  MIDI_CTRL_EFFECT7,      // AKA EFFECT DEPTH 5

  MIDI_CTRL_DATA_INCREMENT,                  // RELEVANT FOR RPN/NRPN
  MIDI_CTRL_DATA_DECREMENT,                  // RELEVANT FOR RPN/NRPN
  MIDI_CTRL_NON_REGISTERED_PARAM_NUMBER_LSB, // RELEVANT FOR RPN/NRPN
  MIDI_CTRL_NON_REGISTERED_PARAM_NUMBER_MSB, // RELEVANT FOR RPN/NRPN
  MIDI_CTRL_REGISTERED_PARAM_NUMBER_LSB,     // RELEVANT FOR RPN/NRPN
  MIDI_CTRL_REGISTERED_PARAM_NUMBER_MSB,     // RELEVANT FOR RPN/NRPN

  MIDI_CTRL_UNDEFINED102,
  MIDI_CTRL_UNDEFINED103,
  MIDI_CTRL_UNDEFINED104,
  MIDI_CTRL_UNDEFINED105,
  MIDI_CTRL_UNDEFINED106,
  MIDI_CTRL_UNDEFINED107,
  MIDI_CTRL_UNDEFINED108,
  MIDI_CTRL_UNDEFINED109,
  MIDI_CTRL_UNDEFINED110,
  MIDI_CTRL_UNDEFINED111,
  MIDI_CTRL_UNDEFINED112,
  MIDI_CTRL_UNDEFINED113,
  MIDI_CTRL_UNDEFINED114,
  MIDI_CTRL_UNDEFINED115,
  MIDI_CTRL_UNDEFINED116,
  MIDI_CTRL_UNDEFINED117,
  MIDI_CTRL_UNDEFINED118,
  MIDI_CTRL_UNDEFINED119,

  MIDI_CTRL_ALL_SOUND_OFF = 120,   // CHANNEL MODE MESSAGE
  MIDI_CTRL_RESET_ALL_CONTROLLERS, // CHANNEL MODE MESSAGE
  MIDI_CTRL_LOCAL_ON_OFF,          // CHANNEL MODE MESSAGE
  MIDI_CTRL_ALL_NOTES_OFF,         // CHANNEL MODE MESSAGE
  MIDI_CTRL_OMNI_MODE_ON,          // CHANNEL MODE MESSAGE
  MIDI_CTRL_OMNI_MODE_OFF,         // CHANNEL MODE MESSAGE
  MIDI_CTRL_MONO_MODE,             // CHANNEL MODE MESSAGE
  MIDI_CTRL_POLY_MODE              // CHANNEL MODE MESSAGE
} MIDI_Control;

static inline MIDI_Control MIDI_u8_to_ctrl(uint8_t u) { return (MIDI_Control)(u); }
static inline uint8_t      MIDI_ctrl_to_u8(MIDI_Control ctrl) { return (uint8_t)(ctrl); }

static inline const char * MIDI_ctrl_to_str(MIDI_Control ctrl) {
  switch(ctrl) {
  case MIDI_CTRL_BANK_SELECT: return "BANK_SELECT";
  case MIDI_CTRL_MOD_WHEEL: return "MOD_WHEEL";
  case MIDI_CTRL_BREATH_CONTROL: return "BREATH_CONTROL";

  case MIDI_CTRL_UNDEFINED3: return "UNDEFINED3";

  case MIDI_CTRL_FOOT_PEDAL: return "FOOT_PEDAL";
  case MIDI_CTRL_PORTAMENTO: return "PORTAMENTO";
  case MIDI_CTRL_DATA_ENTRY: return "DATA_ENTRY";
  case MIDI_CTRL_VOLUME: return "VOLUME";
  case MIDI_CTRL_BALANCE: return "BALANCE";
  case MIDI_CTRL_UNDEFINED9: return "UNDEFINED9";
  case MIDI_CTRL_PAN: return "PAN";
  case MIDI_CTRL_EXPRESSION: return "EXPRESSION";
  case MIDI_CTRL_EFFECT1: return "EFFECT1";
  case MIDI_CTRL_EFFECT2: return "EFFECT2";

  case MIDI_CTRL_UNDEFINED14: return "UNDEFINED14";
  case MIDI_CTRL_UNDEFINED15: return "UNDEFINED15";

  case MIDI_CTRL_GENERAL_A: return "GENERAL_A";
  case MIDI_CTRL_GENERAL_B: return "GENERAL_B";
  case MIDI_CTRL_GENERAL_C: return "GENERAL_C";
  case MIDI_CTRL_GENERAL_D: return "GENERAL_D";

  case MIDI_CTRL_UNDEFINED20: return "UNDEFINED20";
  case MIDI_CTRL_UNDEFINED21: return "UNDEFINED21";
  case MIDI_CTRL_UNDEFINED22: return "UNDEFINED22";
  case MIDI_CTRL_UNDEFINED23: return "UNDEFINED23";
  case MIDI_CTRL_UNDEFINED24: return "UNDEFINED24";
  case MIDI_CTRL_UNDEFINED25: return "UNDEFINED25";
  case MIDI_CTRL_UNDEFINED26: return "UNDEFINED26";
  case MIDI_CTRL_UNDEFINED27: return "UNDEFINED27";
  case MIDI_CTRL_UNDEFINED28: return "UNDEFINED28";
  case MIDI_CTRL_UNDEFINED29: return "UNDEFINED29";
  case MIDI_CTRL_UNDEFINED30: return "UNDEFINED30";
  case MIDI_CTRL_UNDEFINED31: return "UNDEFINED31";

  case MIDI_CTRL_BANK_SELECT_LSB: return "BANK_SELECT_LSB";
  case MIDI_CTRL_MOD_WHEEL_LSB: return "MOD_WHEEL_LSB";
  case MIDI_CTRL_BREATH_CONTROL_LSB: return "BREATH_CONTROL_LSB";

  case MIDI_CTRL_UNDEFINED35: return "UNDEFINED35";

  case MIDI_CTRL_FOOT_PEDAL_LSB: return "FOOT_PEDAL_LSB";
  case MIDI_CTRL_PORTAMENTO_LSB: return "PORTAMENTO_LSB";
  case MIDI_CTRL_DATA_ENTRY_LSB: return "DATA_ENTRY_LSB";
  case MIDI_CTRL_VOLUME_LSB: return "VOLUME_LSB";
  case MIDI_CTRL_BALANCE_LSB: return "BALANCE_LSB";

  case MIDI_CTRL_UNDEFINED41: return "UNDEFINED41";

  case MIDI_CTRL_PAN_LSB: return "PAN_LSB";
  case MIDI_CTRL_EXPRESSION_LSB: return "EXPRESSION_LSB";
  case MIDI_CTRL_EFFECT1_LSB: return "EFFECT1_LSB";
  case MIDI_CTRL_EFFECT2_LSB: return "EFFECT2_LSB";

  case MIDI_CTRL_UNDEFINED46: return "UNDEFINED46";
  case MIDI_CTRL_UNDEFINED47: return "UNDEFINED47";

  case MIDI_CTRL_GENERAL_A_LSB: return "GENERAL_A_LSB";
  case MIDI_CTRL_GENERAL_B_LSB: return "GENERAL_B_LSB";
  case MIDI_CTRL_GENERAL_C_LSB: return "GENERAL_C_LSB";
  case MIDI_CTRL_GENERAL_D_LSB: return "GENERAL_D_LSB";

  case MIDI_CTRL_UNDEFINED52: return "UNDEFINED52";
  case MIDI_CTRL_UNDEFINED53: return "UNDEFINED53";
  case MIDI_CTRL_UNDEFINED54: return "UNDEFINED54";
  case MIDI_CTRL_UNDEFINED55: return "UNDEFINED55";
  case MIDI_CTRL_UNDEFINED56: return "UNDEFINED56";
  case MIDI_CTRL_UNDEFINED57: return "UNDEFINED57";
  case MIDI_CTRL_UNDEFINED58: return "UNDEFINED58";
  case MIDI_CTRL_UNDEFINED59: return "UNDEFINED59";
  case MIDI_CTRL_UNDEFINED60: return "UNDEFINED60";
  case MIDI_CTRL_UNDEFINED61: return "UNDEFINED61";
  case MIDI_CTRL_UNDEFINED62: return "UNDEFINED62";
  case MIDI_CTRL_UNDEFINED63: return "UNDEFINED63";

  case MIDI_CTRL_DAMPER_PEDAL_ON_OFF: return "DAMPER_PEDAL_ON_OFF";
  case MIDI_CTRL_PORTAMENTO_ON_OFF: return "PORTAMENTO_ON_OFF";
  case MIDI_CTRL_SOSTENUTO_PEDAL_ON_OFF: return "SOSTENUTO_PEDAL_ON_OFF";
  case MIDI_CTRL_SOFT_PEDAL_ON_OFF: return "SOFT_PEDAL_ON_OFF";
  case MIDI_CTRL_LEGATO_ON_OFF: return "LEGATO_ON_OFF";
  case MIDI_CTRL_HOLD_ON_OFF: return "HOLD_ON_OFF";

  case MIDI_CTRL_SOUND_VARIATION: return "SOUND_VARIATION";
  case MIDI_CTRL_RESONANCE: return "RESONANCE";
  case MIDI_CTRL_RELEASE_TIME: return "RELEASE_TIME";
  case MIDI_CTRL_ATTACK_TIME: return "ATTACK_TIME";
  case MIDI_CTRL_CUTOFF_FREQUENCY: return "CUTOFF_FREQUENCY";
  case MIDI_CTRL_SOUND_CONTROLLER6: return "SOUND_CONTROLLER6";
  case MIDI_CTRL_SOUND_CONTROLLER7: return "SOUND_CONTROLLER7";
  case MIDI_CTRL_SOUND_CONTROLLER8: return "SOUND_CONTROLLER8";
  case MIDI_CTRL_SOUND_CONTROLLER9: return "SOUND_CONTROLLER9";
  case MIDI_CTRL_SOUND_CONTROLLER10: return "SOUND_CONTROLLER10";

  case MIDI_CTRL_GENERAL_E: return "GENERAL_E";
  case MIDI_CTRL_GENERAL_F: return "GENERAL_F";
  case MIDI_CTRL_GENERAL_G: return "GENERAL_G";
  case MIDI_CTRL_GENERAL_H: return "GENERAL_H";
  case MIDI_CTRL_PORTAMENTO_ALT: return "PORTAMENTO_ALT";

  case MIDI_CTRL_UNDEFINED85: return "UNDEFINED85";
  case MIDI_CTRL_UNDEFINED86: return "UNDEFINED86";
  case MIDI_CTRL_UNDEFINED87: return "UNDEFINED87";

  case MIDI_CTRL_VELOCITY_PREFIX: return "VELOCITY_PREFIX";

  case MIDI_CTRL_UNDEFINED89: return "UNDEFINED89";
  case MIDI_CTRL_UNDEFINED90: return "UNDEFINED90";

  case MIDI_CTRL_EFFECT3: return "EFFECT3";
  case MIDI_CTRL_EFFECT4: return "EFFECT4";
  case MIDI_CTRL_EFFECT5: return "EFFECT5";
  case MIDI_CTRL_EFFECT6: return "EFFECT6";
  case MIDI_CTRL_EFFECT7: return "EFFECT7";

  case MIDI_CTRL_DATA_INCREMENT: return "DATA_INCREMENT";
  case MIDI_CTRL_DATA_DECREMENT: return "DATA_DECREMENT";
  case MIDI_CTRL_NON_REGISTERED_PARAM_NUMBER_LSB: return "NON_REGISTERED_PARAM_NUMBER_LSB";
  case MIDI_CTRL_NON_REGISTERED_PARAM_NUMBER_MSB: return "NON_REGISTERED_PARAM_NUMBER_MSB";
  case MIDI_CTRL_REGISTERED_PARAM_NUMBER_LSB: return "REGISTERED_PARAM_NUMBER_LSB";
  case MIDI_CTRL_REGISTERED_PARAM_NUMBER_MSB: return "REGISTERED_PARAM_NUMBER_MSB";

  case MIDI_CTRL_UNDEFINED102: return "UNDEFINED102";
  case MIDI_CTRL_UNDEFINED103: return "UNDEFINED103";
  case MIDI_CTRL_UNDEFINED104: return "UNDEFINED104";
  case MIDI_CTRL_UNDEFINED105: return "UNDEFINED105";
  case MIDI_CTRL_UNDEFINED106: return "UNDEFINED106";
  case MIDI_CTRL_UNDEFINED107: return "UNDEFINED107";
  case MIDI_CTRL_UNDEFINED108: return "UNDEFINED108";
  case MIDI_CTRL_UNDEFINED109: return "UNDEFINED109";
  case MIDI_CTRL_UNDEFINED110: return "UNDEFINED110";
  case MIDI_CTRL_UNDEFINED111: return "UNDEFINED111";
  case MIDI_CTRL_UNDEFINED112: return "UNDEFINED112";
  case MIDI_CTRL_UNDEFINED113: return "UNDEFINED113";
  case MIDI_CTRL_UNDEFINED114: return "UNDEFINED114";
  case MIDI_CTRL_UNDEFINED115: return "UNDEFINED115";
  case MIDI_CTRL_UNDEFINED116: return "UNDEFINED116";
  case MIDI_CTRL_UNDEFINED117: return "UNDEFINED117";
  case MIDI_CTRL_UNDEFINED118: return "UNDEFINED118";
  case MIDI_CTRL_UNDEFINED119: return "UNDEFINED119";

  case MIDI_CTRL_ALL_SOUND_OFF: return "ALL_SOUND_OFF";
  case MIDI_CTRL_RESET_ALL_CONTROLLERS: return "RESET_ALL_CONTROLLERS";
  case MIDI_CTRL_LOCAL_ON_OFF: return "LOCAL_ON_OFF";
  case MIDI_CTRL_ALL_NOTES_OFF: return "ALL_NOTES_OFF";
  case MIDI_CTRL_OMNI_MODE_ON: return "OMNI_MODE_ON";
  case MIDI_CTRL_OMNI_MODE_OFF: return "OMNI_MODE_OFF";
  case MIDI_CTRL_MONO_MODE: return "MONO_MODE";
  case MIDI_CTRL_POLY_MODE: return "POLY_MODE";
  default: return "OTHER";
  }
}

#endif